from app.schemas.rating_schema import RatingRequest, RatingResponse
from app.models.rating_model import Rating
from app.repositories.rating_repository import RatingRepository
from app.llm.prompt_builder import build_rating_prompt
from app.llm.llm_client import call_llm
from app.llm.output_parser import parse_llm_output


class RatingService:
    """
    Service layer responsible for evaluating DM–Reporter training efficiency.

    This service orchestrates the core business logic of the application. It
    processes rating inputs, stores the rating data, interacts with the LLM
    to evaluate training efficiency, and returns the structured result.

    Responsibilities:
    - Convert API request data into internal domain objects
    - Persist rating information using the repository layer
    - Build prompts for the AI model
    - Call the LLM to analyze the ratings
    - Parse the AI response into structured output
    """
    def __init__(self):
        """
        Initialize the RatingService.

        Creates an instance of RatingRepository used to store rating data.
        """
        self.repo = RatingRepository()

    def evaluate_rating(self, data: RatingRequest) -> RatingResponse:
        """
        Evaluate training efficiency between a District Manager (DM)
        and a Reporter using an AI model.

        Workflow:
        1. Convert the incoming RatingRequest into a Rating domain object.
        2. Store the rating information using the repository.
        3. Generate a prompt based on DM teaching and reporter learning ratings.
        4. Send the prompt to the LLM for evaluation.
        5. Parse the AI response to extract efficiency score and feedback.
        6. Return the result as a structured RatingResponse.

        Args:
            data (RatingRequest):
                Input data containing:
                - dm_id
                - reporter_id
                - dm_teaching_rating
                - reporter_learning_rating

        Returns:
            RatingResponse:
                Structured response containing:
                - dm_id
                - reporter_id
                - ai_efficiency_score
                - feedback generated by the AI model
        """
        rating = Rating(
            dm_id=data.dm_id,
            reporter_id=data.reporter_id,
            dm_teaching_rating=data.dm_teaching_rating,
            reporter_learning_rating=data.reporter_learning_rating
        )

        self.repo.save(rating)

        prompt = build_rating_prompt(
            rating.dm_teaching_rating,
            rating.reporter_learning_rating
        )

        llm_output = call_llm(prompt)

        parsed = parse_llm_output(llm_output)

        return RatingResponse(
            dm_id=rating.dm_id,
            reporter_id=rating.reporter_id,
            ai_efficiency_score=parsed["efficiency_score"],
            feedback=parsed["feedback"]
        )